# Cloudflare Pages 配置文件

name = "sparkdone-blog"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages 配置
pages_build_output_dir = "dist"

# 环境变量
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"

# KV 存储绑定 (用于缓存)
[[kv_namespaces]]
binding = "CACHE_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# D1 数据库绑定 (如果需要)
# [[d1_databases]]
# binding = "DB"
# database_name = "sparkdone-db"
# database_id = "your-database-id"

# 自定义域名
# [env.production]
# routes = [
#   { pattern = "sparkdone.com", custom_domain = true },
#   { pattern = "www.sparkdone.com", custom_domain = true }
# ]
